// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PreflightApi.Infrastructure.Data;

#nullable disable

namespace PreflightApi.Infrastructure.Migrations
{
    [DbContext(typeof(PreflightApiDbContext))]
    [Migration("20250207204108_ChangingAirportEntityKey")]
    partial class ChangingAirportEntityKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PreflightApi.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Acreage")
                        .HasColumnType("integer")
                        .HasColumnName("acreage");

                    b.Property<string>("ActivationDate")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("activation_date");

                    b.Property<string>("AdoCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ado_code");

                    b.Property<string>("AirframeRepairSerCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("airframe_repair_ser_code");

                    b.Property<string>("ArptElevSource")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("arpt_elev_source");

                    b.Property<string>("ArptId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("arpt_id");

                    b.Property<string>("ArptName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arpt_name");

                    b.Property<string>("ArptPsnSource")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("arpt_psn_source");

                    b.Property<string>("ArptStatus")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("arpt_status");

                    b.Property<string>("AttendanceDay")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("attendance_day");

                    b.Property<string>("AttendanceHours")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("attendance_hours");

                    b.Property<string>("AttendanceMonth")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("attendance_month");

                    b.Property<string>("BcnLensColor")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("bcn_lens_color");

                    b.Property<string>("BcnLgtSked")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("bcn_lgt_sked");

                    b.Property<string>("BottledOxyType")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("bottled_oxy_type");

                    b.Property<string>("BulkOxyType")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("bulk_oxy_type");

                    b.Property<string>("ChartName")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("chart_name");

                    b.Property<string>("City")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("city");

                    b.Property<string>("ContactAddress1")
                        .HasColumnType("varchar(35)")
                        .HasColumnName("contact_address1");

                    b.Property<string>("ContactAddress2")
                        .HasColumnType("varchar(35)")
                        .HasColumnName("contact_address2");

                    b.Property<string>("ContactCity")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("contact_city");

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(35)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("contact_phone_number");

                    b.Property<string>("ContactState")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("contact_state");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contact_title");

                    b.Property<string>("ContactZipCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("contact_zip_code");

                    b.Property<string>("ContactZipPlusFour")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("contact_zip_plus_four");

                    b.Property<string>("ContrFuelAvbl")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("contr_fuel_avbl");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountyAssocState")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("county_assoc_state");

                    b.Property<string>("CountyName")
                        .HasColumnType("varchar(21)")
                        .HasColumnName("county_name");

                    b.Property<string>("Cta")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("cta");

                    b.Property<string>("CustomsFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("customs_flag");

                    b.Property<string>("DirectionCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("direction_code");

                    b.Property<decimal?>("DistCityToAirport")
                        .HasColumnType("decimal(2,0)")
                        .HasColumnName("dist_city_to_airport");

                    b.Property<DateTime>("EffDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eff_date");

                    b.Property<decimal?>("Elev")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("elev");

                    b.Property<string>("ElevMethodCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("elev_method_code");

                    b.Property<DateTime?>("ElevationSrcDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("elevation_src_date");

                    b.Property<string>("FacilityUseCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("facility_use_code");

                    b.Property<string>("FssId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("fss_id");

                    b.Property<string>("FssName")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fss_name");

                    b.Property<string>("FssOnArptFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("fss_on_arpt_flag");

                    b.Property<string>("FuelTypes")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("fuel_types");

                    b.Property<string>("IcaoId")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("icao_id");

                    b.Property<string>("InspectMethodCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("inspect_method_code");

                    b.Property<string>("InspectorCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("inspector_code");

                    b.Property<string>("JointUseFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("joint_use_flag");

                    b.Property<DateTime?>("LastInfoResponse")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_info_response");

                    b.Property<DateTime?>("LastInspection")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inspection");

                    b.Property<decimal?>("LatDecimal")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("lat_decimal");

                    b.Property<int?>("LatDeg")
                        .HasColumnType("int")
                        .HasColumnName("lat_deg");

                    b.Property<string>("LatHemis")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lat_hemis");

                    b.Property<int?>("LatMin")
                        .HasColumnType("int")
                        .HasColumnName("lat_min");

                    b.Property<decimal?>("LatSec")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("lat_sec");

                    b.Property<string>("LgtSked")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("lgt_sked");

                    b.Property<string>("LndgFeeFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lndg_fee_flag");

                    b.Property<string>("LndgRightsFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lndg_rights_flag");

                    b.Property<decimal?>("LongDecimal")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("long_decimal");

                    b.Property<int?>("LongDeg")
                        .HasColumnType("int")
                        .HasColumnName("long_deg");

                    b.Property<string>("LongHemis")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("long_hemis");

                    b.Property<int?>("LongMin")
                        .HasColumnType("int")
                        .HasColumnName("long_min");

                    b.Property<decimal?>("LongSec")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("long_sec");

                    b.Property<string>("MagHemis")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("mag_hemis");

                    b.Property<decimal?>("MagVarn")
                        .HasColumnType("decimal(2,0)")
                        .HasColumnName("mag_varn");

                    b.Property<int?>("MagVarnYear")
                        .HasColumnType("integer")
                        .HasColumnName("mag_varn_year");

                    b.Property<string>("MedicalUseFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("medical_use_flag");

                    b.Property<string>("MilLndgFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("mil_lndg_flag");

                    b.Property<string>("MinOpNetwork")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("min_op_network");

                    b.Property<string>("NaspCode")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("nasp_code");

                    b.Property<string>("NotamFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("notam_flag");

                    b.Property<string>("NotamId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("notam_id");

                    b.Property<string>("OtherServices")
                        .HasColumnType("varchar(110)")
                        .HasColumnName("other_services");

                    b.Property<string>("OwnershipTypeCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("ownership_type_code");

                    b.Property<DateTime?>("PositionSrcDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("position_src_date");

                    b.Property<string>("PwrPlantRepairSer")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("pwr_plant_repair_ser");

                    b.Property<string>("RegionCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("region_code");

                    b.Property<string>("RespArtccId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("resp_artcc_id");

                    b.Property<string>("SegCircleMkrFlag")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("seg_circle_mkr_flag");

                    b.Property<string>("SiteNo")
                        .IsRequired()
                        .HasColumnType("varchar(9)")
                        .HasColumnName("site_no");

                    b.Property<string>("SiteTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("site_type_code");

                    b.Property<int?>("SkedSeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("sked_seq_no");

                    b.Property<string>("StateCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("StateName")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("state_name");

                    b.Property<string>("SurveyMethodCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("survey_method_code");

                    b.Property<int?>("Tpa")
                        .HasColumnType("integer")
                        .HasColumnName("tpa");

                    b.Property<string>("TrnsStrgBuoyFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("trns_strg_buoy_flag");

                    b.Property<string>("TrnsStrgHgrFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("trns_strg_hgr_flag");

                    b.Property<string>("TrnsStrgTieFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("trns_strg_tie_flag");

                    b.Property<string>("TwrTypeCode")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("twr_type_code");

                    b.Property<string>("UserFeeFlag")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("user_fee_flag");

                    b.Property<string>("WindIndcrFlag")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("wind_indcr_flag");

                    b.HasKey("Id");

                    b.HasIndex("ArptId");

                    b.HasIndex("IcaoId");

                    b.HasIndex("StateCode");

                    b.HasIndex("LatDecimal", "LongDecimal");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.AirportDiagram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportIdent")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("airport_ident");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("airport_name");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_name");

                    b.Property<string>("IcaoIdent")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("icao_ident");

                    b.HasKey("Id");

                    b.HasIndex("AirportIdent");

                    b.HasIndex("IcaoIdent");

                    b.ToTable("airport_diagrams", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Airsigmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirsigmetType")
                        .HasColumnType("text")
                        .HasColumnName("airsigmet_type");

                    b.Property<string>("Altitude")
                        .HasColumnType("jsonb")
                        .HasColumnName("altitude");

                    b.Property<string>("Areas")
                        .HasColumnType("jsonb")
                        .HasColumnName("area");

                    b.Property<string>("Hazard")
                        .HasColumnType("jsonb")
                        .HasColumnName("hazard");

                    b.Property<int?>("MovementDirDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("movement_dir_degrees");

                    b.Property<int?>("MovementSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("movement_speed_kt");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("ValidTimeFrom")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_from");

                    b.Property<string>("ValidTimeTo")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_to");

                    b.HasKey("Id");

                    b.HasIndex("AirsigmetType");

                    b.HasIndex("ValidTimeFrom");

                    b.HasIndex("ValidTimeTo");

                    b.ToTable("airsigmet");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.ChartSupplement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportCity")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("airport_city");

                    b.Property<string>("AirportCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("airport_code");

                    b.Property<string>("AirportName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("airport_name");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("NavigationalAidName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("navigational_aid_name");

                    b.HasKey("Id");

                    b.HasIndex("AirportCode");

                    b.HasIndex("NavigationalAidName");

                    b.ToTable("chart_supplement");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.FaaPublicationCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleLengthDays")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_length_days");

                    b.Property<DateTime>("KnownValidDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("known_valid_date");

                    b.Property<DateTime?>("LastSuccessfulUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_update");

                    b.Property<string>("PublicationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publication_type");

                    b.HasKey("Id");

                    b.HasIndex("PublicationType")
                        .IsUnique();

                    b.ToTable("faa_publication_cycle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CycleLengthDays = 56,
                            KnownValidDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "ChartSupplement"
                        },
                        new
                        {
                            Id = 2,
                            CycleLengthDays = 28,
                            KnownValidDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "AirportDiagram"
                        },
                        new
                        {
                            Id = 3,
                            CycleLengthDays = 28,
                            KnownValidDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "NasrSubscription"
                        });
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Pirep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftRef")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_ref");

                    b.Property<int?>("AltitudeFtMsl")
                        .HasColumnType("integer")
                        .HasColumnName("altitude_ft_msl");

                    b.Property<string>("IcingConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("icing_condition");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<string>("ObservationTime")
                        .HasColumnType("text")
                        .HasColumnName("observation_time");

                    b.Property<string>("QualityControlFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_control_flags");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("ReceiptTime")
                        .HasColumnType("text")
                        .HasColumnName("receipt_time");

                    b.Property<string>("ReportType")
                        .HasColumnType("text")
                        .HasColumnName("report_type");

                    b.Property<string>("SkyConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("sky_condition");

                    b.Property<float?>("TempC")
                        .HasColumnType("real")
                        .HasColumnName("temp_c");

                    b.Property<string>("TurbulenceConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("turbulence_condition");

                    b.Property<int?>("VertGustKt")
                        .HasColumnType("integer")
                        .HasColumnName("vert_gust_kt");

                    b.Property<int?>("VisibilityStatuteMi")
                        .HasColumnType("integer")
                        .HasColumnName("visibility_statute_mi");

                    b.Property<int?>("WindDirDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("wind_dir_degrees");

                    b.Property<int?>("WindSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_speed_kt");

                    b.Property<string>("WxString")
                        .HasColumnType("text")
                        .HasColumnName("wx_string");

                    b.HasKey("Id");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("ReceiptTime");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("pirep");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Taf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BulletinTime")
                        .HasColumnType("text")
                        .HasColumnName("bulletin_time");

                    b.Property<float?>("ElevationM")
                        .HasColumnType("real")
                        .HasColumnName("elevation_m");

                    b.Property<string>("Forecast")
                        .HasColumnType("jsonb")
                        .HasColumnName("forecast");

                    b.Property<string>("IssueTime")
                        .HasColumnType("text")
                        .HasColumnName("issue_time");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("StationId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("station_id");

                    b.Property<string>("ValidTimeFrom")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_from");

                    b.Property<string>("ValidTimeTo")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_to");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("ValidTimeFrom");

                    b.HasIndex("StationId", "ValidTimeFrom");

                    b.ToTable("taf");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Metar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AltimInHg")
                        .HasColumnType("real")
                        .HasColumnName("altim_in_hg");

                    b.Property<float?>("DewpointC")
                        .HasColumnType("real")
                        .HasColumnName("dewpoint_c");

                    b.Property<float?>("ElevationM")
                        .HasColumnType("real")
                        .HasColumnName("elevation_m");

                    b.Property<string>("FlightCategory")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("flight_category");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<float?>("MaxT24hrC")
                        .HasColumnType("real")
                        .HasColumnName("maxT24hr_c");

                    b.Property<float?>("MaxTC")
                        .HasColumnType("real")
                        .HasColumnName("maxT_c");

                    b.Property<string>("MetarType")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("metar_type");

                    b.Property<float?>("MinT24hrC")
                        .HasColumnType("real")
                        .HasColumnName("minT24hr_c");

                    b.Property<float?>("MinTC")
                        .HasColumnType("real")
                        .HasColumnName("minT_c");

                    b.Property<string>("ObservationTime")
                        .HasColumnType("text")
                        .HasColumnName("observation_time");

                    b.Property<float?>("Pcp24hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp24hr_in");

                    b.Property<float?>("Pcp3hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp3hr_in");

                    b.Property<float?>("Pcp6hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp6hr_in");

                    b.Property<float?>("PrecipIn")
                        .HasColumnType("real")
                        .HasColumnName("precip_in");

                    b.Property<string>("QualityControlFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_control_flags");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<float?>("SeaLevelPressureMb")
                        .HasColumnType("real")
                        .HasColumnName("sea_level_pressure_mb");

                    b.Property<string>("SkyCondition")
                        .HasColumnType("jsonb")
                        .HasColumnName("sky_condition");

                    b.Property<float?>("SnowIn")
                        .HasColumnType("real")
                        .HasColumnName("snow_in");

                    b.Property<string>("StationId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("station_id");

                    b.Property<float?>("TempC")
                        .HasColumnType("real")
                        .HasColumnName("temp_c");

                    b.Property<float?>("ThreeHrPressureTendencyMb")
                        .HasColumnType("real")
                        .HasColumnName("three_hr_pressure_tendency_mb");

                    b.Property<int?>("VertVisFt")
                        .HasColumnType("integer")
                        .HasColumnName("vert_vis_ft");

                    b.Property<string>("VisibilityStatuteMi")
                        .HasColumnType("text")
                        .HasColumnName("visibility_statute_mi");

                    b.Property<string>("WindDirDegrees")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("wind_dir_degrees");

                    b.Property<int?>("WindGustKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_gust_kt");

                    b.Property<int?>("WindSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_speed_kt");

                    b.Property<string>("WxString")
                        .HasColumnType("text")
                        .HasColumnName("wx_string");

                    b.HasKey("Id");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("StationId");

                    b.HasIndex("StationId", "ObservationTime");

                    b.ToTable("metar");
                });
#pragma warning restore 612, 618
        }
    }
}
