// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PreflightApi.Infrastructure.Data;

#nullable disable

namespace PreflightApi.Infrastructure.Migrations
{
    [DbContext(typeof(PreflightApiDbContext))]
    [Migration("20250111043555_AddedAirsigmetEntity")]
    partial class AddedAirsigmetEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PreflightApi.Domain.Entities.Airsigmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirsigmetType")
                        .HasColumnType("text")
                        .HasColumnName("airsigmet_type");

                    b.Property<string>("Altitude")
                        .HasColumnType("jsonb")
                        .HasColumnName("altitude");

                    b.Property<string>("Areas")
                        .HasColumnType("jsonb")
                        .HasColumnName("area");

                    b.Property<string>("Hazard")
                        .HasColumnType("jsonb")
                        .HasColumnName("hazard");

                    b.Property<int?>("MovementDirDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("movement_dir_degrees");

                    b.Property<int?>("MovementSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("movement_speed_kt");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("ValidTimeFrom")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_from");

                    b.Property<string>("ValidTimeTo")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_to");

                    b.HasKey("Id");

                    b.HasIndex("AirsigmetType");

                    b.HasIndex("ValidTimeFrom");

                    b.HasIndex("ValidTimeTo");

                    b.ToTable("airsigmet");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Pirep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftRef")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_ref");

                    b.Property<int?>("AltitudeFtMsl")
                        .HasColumnType("integer")
                        .HasColumnName("altitude_ft_msl");

                    b.Property<string>("IcingConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("icing_condition");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<string>("ObservationTime")
                        .HasColumnType("text")
                        .HasColumnName("observation_time");

                    b.Property<string>("QualityControlFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_control_flags");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("ReceiptTime")
                        .HasColumnType("text")
                        .HasColumnName("receipt_time");

                    b.Property<string>("ReportType")
                        .HasColumnType("text")
                        .HasColumnName("report_type");

                    b.Property<string>("SkyConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("sky_condition");

                    b.Property<float?>("TempC")
                        .HasColumnType("real")
                        .HasColumnName("temp_c");

                    b.Property<string>("TurbulenceConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("turbulence_condition");

                    b.Property<int?>("VertGustKt")
                        .HasColumnType("integer")
                        .HasColumnName("vert_gust_kt");

                    b.Property<int?>("VisibilityStatuteMi")
                        .HasColumnType("integer")
                        .HasColumnName("visibility_statute_mi");

                    b.Property<int?>("WindDirDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("wind_dir_degrees");

                    b.Property<int?>("WindSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_speed_kt");

                    b.Property<string>("WxString")
                        .HasColumnType("text")
                        .HasColumnName("wx_string");

                    b.HasKey("Id");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("ReceiptTime");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("pirep");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Taf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BulletinTime")
                        .HasColumnType("text")
                        .HasColumnName("bulletin_time");

                    b.Property<float?>("ElevationM")
                        .HasColumnType("real")
                        .HasColumnName("elevation_m");

                    b.Property<string>("Forecast")
                        .HasColumnType("jsonb")
                        .HasColumnName("forecast");

                    b.Property<string>("IssueTime")
                        .HasColumnType("text")
                        .HasColumnName("issue_time");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("StationId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("station_id");

                    b.Property<string>("ValidTimeFrom")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_from");

                    b.Property<string>("ValidTimeTo")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_to");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("ValidTimeFrom");

                    b.HasIndex("StationId", "ValidTimeFrom");

                    b.ToTable("taf");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Metar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AltimInHg")
                        .HasColumnType("real")
                        .HasColumnName("altim_in_hg");

                    b.Property<float?>("DewpointC")
                        .HasColumnType("real")
                        .HasColumnName("dewpoint_c");

                    b.Property<float?>("ElevationM")
                        .HasColumnType("real")
                        .HasColumnName("elevation_m");

                    b.Property<string>("FlightCategory")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("flight_category");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<float?>("MaxT24hrC")
                        .HasColumnType("real")
                        .HasColumnName("maxT24hr_c");

                    b.Property<float?>("MaxTC")
                        .HasColumnType("real")
                        .HasColumnName("maxT_c");

                    b.Property<string>("MetarType")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("metar_type");

                    b.Property<float?>("MinT24hrC")
                        .HasColumnType("real")
                        .HasColumnName("minT24hr_c");

                    b.Property<float?>("MinTC")
                        .HasColumnType("real")
                        .HasColumnName("minT_c");

                    b.Property<string>("ObservationTime")
                        .HasColumnType("text")
                        .HasColumnName("observation_time");

                    b.Property<float?>("Pcp24hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp24hr_in");

                    b.Property<float?>("Pcp3hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp3hr_in");

                    b.Property<float?>("Pcp6hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp6hr_in");

                    b.Property<float?>("PrecipIn")
                        .HasColumnType("real")
                        .HasColumnName("precip_in");

                    b.Property<string>("QualityControlFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_control_flags");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<float?>("SeaLevelPressureMb")
                        .HasColumnType("real")
                        .HasColumnName("sea_level_pressure_mb");

                    b.Property<string>("SkyCondition")
                        .HasColumnType("jsonb")
                        .HasColumnName("sky_condition");

                    b.Property<float?>("SnowIn")
                        .HasColumnType("real")
                        .HasColumnName("snow_in");

                    b.Property<string>("StationId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("station_id");

                    b.Property<float?>("TempC")
                        .HasColumnType("real")
                        .HasColumnName("temp_c");

                    b.Property<float?>("ThreeHrPressureTendencyMb")
                        .HasColumnType("real")
                        .HasColumnName("three_hr_pressure_tendency_mb");

                    b.Property<int?>("VertVisFt")
                        .HasColumnType("integer")
                        .HasColumnName("vert_vis_ft");

                    b.Property<string>("VisibilityStatuteMi")
                        .HasColumnType("text")
                        .HasColumnName("visibility_statute_mi");

                    b.Property<string>("WindDirDegrees")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("wind_dir_degrees");

                    b.Property<int?>("WindGustKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_gust_kt");

                    b.Property<int?>("WindSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_speed_kt");

                    b.Property<string>("WxString")
                        .HasColumnType("text")
                        .HasColumnName("wx_string");

                    b.HasKey("Id");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("StationId");

                    b.HasIndex("StationId", "ObservationTime");

                    b.ToTable("metar");
                });
#pragma warning restore 612, 618
        }
    }
}
