// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PreflightApi.Domain.ValueObjects.Flights;
using PreflightApi.Domain.ValueObjects.WeightBalance;
using PreflightApi.Infrastructure.Data;

#nullable disable

namespace PreflightApi.Infrastructure.Migrations
{
    [DbContext(typeof(PreflightApiDbContext))]
    [Migration("20260127183157_AddWeightBalanceProfile")]
    partial class AddWeightBalanceProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PreflightApi.Domain.Entities.Aircraft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftHome")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("aircraft_home");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("aircraft_type");

                    b.Property<string>("AirspeedUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("airspeed_units");

                    b.Property<string>("CallSign")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("call_sign");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Color2")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color2");

                    b.Property<string>("Color3")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color3");

                    b.Property<string>("Color4")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color4");

                    b.Property<int?>("DefaultCruiseAltitude")
                        .HasColumnType("integer")
                        .HasColumnName("default_cruise_altitude");

                    b.Property<double?>("GlideRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("glide_ratio");

                    b.Property<int?>("GlideSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("glide_speed");

                    b.Property<string>("LengthUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("length_units");

                    b.Property<int?>("MaxCeiling")
                        .HasColumnType("integer")
                        .HasColumnName("max_ceiling");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("primary_color");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial_number");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tail_number");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TailNumber")
                        .IsUnique();

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.AircraftPerformanceProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftId")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_id");

                    b.Property<int>("ClimbFpm")
                        .HasColumnType("integer")
                        .HasColumnName("climb_fpm");

                    b.Property<double>("ClimbFuelBurn")
                        .HasColumnType("double precision")
                        .HasColumnName("climb_fuel_burn");

                    b.Property<int>("ClimbTrueAirspeed")
                        .HasColumnType("integer")
                        .HasColumnName("climb_true_airspeed");

                    b.Property<double>("CruiseFuelBurn")
                        .HasColumnType("double precision")
                        .HasColumnName("cruise_fuel_burn");

                    b.Property<int>("CruiseTrueAirspeed")
                        .HasColumnType("integer")
                        .HasColumnName("cruise_true_airspeed");

                    b.Property<int>("DescentFpm")
                        .HasColumnType("integer")
                        .HasColumnName("descent_fpm");

                    b.Property<double>("DescentFuelBurn")
                        .HasColumnType("double precision")
                        .HasColumnName("descent_fuel_burn");

                    b.Property<int>("DescentTrueAirspeed")
                        .HasColumnType("integer")
                        .HasColumnName("descent_true_airspeed");

                    b.Property<double>("FuelOnBoardGals")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_on_board_gals");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profile_name");

                    b.Property<double>("SttFuelGals")
                        .HasColumnType("double precision")
                        .HasColumnName("stt_fuel_gals");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProfileName")
                        .IsUnique();

                    b.ToTable("aircraft_performance", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Airport", b =>
                {
                    b.Property<string>("SiteNo")
                        .HasColumnType("varchar(9)")
                        .HasColumnName("site_no");

                    b.Property<int?>("Acreage")
                        .HasColumnType("integer")
                        .HasColumnName("acreage");

                    b.Property<string>("ActivationDate")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("activation_date");

                    b.Property<string>("AdoCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ado_code");

                    b.Property<string>("AirframeRepairSerCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("airframe_repair_ser_code");

                    b.Property<string>("ArptElevSource")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("arpt_elev_source");

                    b.Property<string>("ArptId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("arpt_id");

                    b.Property<string>("ArptName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arpt_name");

                    b.Property<string>("ArptPsnSource")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("arpt_psn_source");

                    b.Property<string>("ArptStatus")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("arpt_status");

                    b.Property<string>("AttendanceDay")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("attendance_day");

                    b.Property<string>("AttendanceHours")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("attendance_hours");

                    b.Property<string>("AttendanceMonth")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("attendance_month");

                    b.Property<string>("BcnLensColor")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("bcn_lens_color");

                    b.Property<string>("BcnLgtSked")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("bcn_lgt_sked");

                    b.Property<string>("BottledOxyType")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("bottled_oxy_type");

                    b.Property<string>("BulkOxyType")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("bulk_oxy_type");

                    b.Property<string>("ChartName")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("chart_name");

                    b.Property<string>("City")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("city");

                    b.Property<string>("ContactAddress1")
                        .HasColumnType("varchar(35)")
                        .HasColumnName("contact_address1");

                    b.Property<string>("ContactAddress2")
                        .HasColumnType("varchar(35)")
                        .HasColumnName("contact_address2");

                    b.Property<string>("ContactCity")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("contact_city");

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(35)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("contact_phone_number");

                    b.Property<string>("ContactState")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("contact_state");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contact_title");

                    b.Property<string>("ContactZipCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("contact_zip_code");

                    b.Property<string>("ContactZipPlusFour")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("contact_zip_plus_four");

                    b.Property<string>("ContrFuelAvbl")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("contr_fuel_avbl");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountyAssocState")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("county_assoc_state");

                    b.Property<string>("CountyName")
                        .HasColumnType("varchar(21)")
                        .HasColumnName("county_name");

                    b.Property<string>("Cta")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("cta");

                    b.Property<string>("CustomsFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("customs_flag");

                    b.Property<string>("DirectionCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("direction_code");

                    b.Property<decimal?>("DistCityToAirport")
                        .HasColumnType("decimal(2,0)")
                        .HasColumnName("dist_city_to_airport");

                    b.Property<DateTime>("EffDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eff_date");

                    b.Property<decimal?>("Elev")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("elev");

                    b.Property<string>("ElevMethodCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("elev_method_code");

                    b.Property<DateTime?>("ElevationSrcDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("elevation_src_date");

                    b.Property<string>("FacilityUseCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("facility_use_code");

                    b.Property<string>("FssId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("fss_id");

                    b.Property<string>("FssName")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fss_name");

                    b.Property<string>("FssOnArptFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("fss_on_arpt_flag");

                    b.Property<string>("FuelTypes")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("fuel_types");

                    b.Property<string>("IcaoId")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("icao_id");

                    b.Property<string>("InspectMethodCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("inspect_method_code");

                    b.Property<string>("InspectorCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("inspector_code");

                    b.Property<string>("JointUseFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("joint_use_flag");

                    b.Property<DateTime?>("LastInfoResponse")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_info_response");

                    b.Property<DateTime?>("LastInspection")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inspection");

                    b.Property<decimal?>("LatDecimal")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("lat_decimal");

                    b.Property<int?>("LatDeg")
                        .HasColumnType("int")
                        .HasColumnName("lat_deg");

                    b.Property<string>("LatHemis")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lat_hemis");

                    b.Property<int?>("LatMin")
                        .HasColumnType("int")
                        .HasColumnName("lat_min");

                    b.Property<decimal?>("LatSec")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("lat_sec");

                    b.Property<string>("LgtSked")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("lgt_sked");

                    b.Property<string>("LndgFeeFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lndg_fee_flag");

                    b.Property<string>("LndgRightsFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lndg_rights_flag");

                    b.Property<decimal?>("LongDecimal")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("long_decimal");

                    b.Property<int?>("LongDeg")
                        .HasColumnType("int")
                        .HasColumnName("long_deg");

                    b.Property<string>("LongHemis")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("long_hemis");

                    b.Property<int?>("LongMin")
                        .HasColumnType("int")
                        .HasColumnName("long_min");

                    b.Property<decimal?>("LongSec")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("long_sec");

                    b.Property<string>("MagHemis")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("mag_hemis");

                    b.Property<decimal?>("MagVarn")
                        .HasColumnType("decimal(2,0)")
                        .HasColumnName("mag_varn");

                    b.Property<int?>("MagVarnYear")
                        .HasColumnType("integer")
                        .HasColumnName("mag_varn_year");

                    b.Property<string>("MedicalUseFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("medical_use_flag");

                    b.Property<string>("MilLndgFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("mil_lndg_flag");

                    b.Property<string>("MinOpNetwork")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("min_op_network");

                    b.Property<string>("NaspCode")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("nasp_code");

                    b.Property<string>("NotamFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("notam_flag");

                    b.Property<string>("NotamId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("notam_id");

                    b.Property<string>("OtherServices")
                        .HasColumnType("varchar(110)")
                        .HasColumnName("other_services");

                    b.Property<string>("OwnershipTypeCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("ownership_type_code");

                    b.Property<DateTime?>("PositionSrcDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("position_src_date");

                    b.Property<string>("PwrPlantRepairSer")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("pwr_plant_repair_ser");

                    b.Property<string>("RegionCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("region_code");

                    b.Property<string>("RespArtccId")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("resp_artcc_id");

                    b.Property<string>("SegCircleMkrFlag")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("seg_circle_mkr_flag");

                    b.Property<string>("SiteTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("site_type_code");

                    b.Property<int?>("SkedSeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("sked_seq_no");

                    b.Property<string>("StateCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("StateName")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("state_name");

                    b.Property<string>("SurveyMethodCode")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("survey_method_code");

                    b.Property<int?>("Tpa")
                        .HasColumnType("integer")
                        .HasColumnName("tpa");

                    b.Property<string>("TrnsStrgBuoyFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("trns_strg_buoy_flag");

                    b.Property<string>("TrnsStrgHgrFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("trns_strg_hgr_flag");

                    b.Property<string>("TrnsStrgTieFlag")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("trns_strg_tie_flag");

                    b.Property<string>("TwrTypeCode")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("twr_type_code");

                    b.Property<string>("UserFeeFlag")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("user_fee_flag");

                    b.Property<string>("WindIndcrFlag")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("wind_indcr_flag");

                    b.HasKey("SiteNo");

                    b.HasIndex("ArptId");

                    b.HasIndex("IcaoId");

                    b.HasIndex("StateCode");

                    b.HasIndex("LatDecimal", "LongDecimal");

                    b.HasIndex("StateCode", "ArptId");

                    b.HasIndex("StateCode", "IcaoId");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.AirportDiagram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportIdent")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("airport_ident");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("airport_name");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_name");

                    b.Property<string>("IcaoIdent")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("icao_ident");

                    b.HasKey("Id");

                    b.HasIndex("AirportIdent");

                    b.HasIndex("IcaoIdent");

                    b.ToTable("airport_diagrams", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Airsigmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirsigmetType")
                        .HasColumnType("text")
                        .HasColumnName("airsigmet_type");

                    b.Property<string>("Altitude")
                        .HasColumnType("jsonb")
                        .HasColumnName("altitude");

                    b.Property<string>("Areas")
                        .HasColumnType("jsonb")
                        .HasColumnName("area");

                    b.Property<string>("Hazard")
                        .HasColumnType("jsonb")
                        .HasColumnName("hazard");

                    b.Property<int?>("MovementDirDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("movement_dir_degrees");

                    b.Property<int?>("MovementSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("movement_speed_kt");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("ValidTimeFrom")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_from");

                    b.Property<string>("ValidTimeTo")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_to");

                    b.HasKey("Id");

                    b.HasIndex("AirsigmetType");

                    b.HasIndex("ValidTimeFrom");

                    b.HasIndex("ValidTimeTo");

                    b.ToTable("airsigmet");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Airspace", b =>
                {
                    b.Property<string>("GlobalId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("global_id");

                    b.Property<string>("AdhpId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adhp_id");

                    b.Property<short?>("AkHigh")
                        .HasColumnType("smallint")
                        .HasColumnName("ak_high");

                    b.Property<short?>("AkLow")
                        .HasColumnType("smallint")
                        .HasColumnName("ak_low");

                    b.Property<string>("City")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("city");

                    b.Property<string>("Class")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("class");

                    b.Property<string>("CommName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("comm_name");

                    b.Property<string>("ContAgent")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("cont_agent");

                    b.Property<string>("Country")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("country");

                    b.Property<string>("Dst")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dst");

                    b.Property<string>("Exclusion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("exclusion");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry(Polygon, 4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("GmtOffset")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("gmt_offset");

                    b.Property<string>("IcaoId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("icao_id");

                    b.Property<string>("Ident")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ident");

                    b.Property<string>("Level")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("level");

                    b.Property<string>("LocalType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("local_type");

                    b.Property<string>("LowerCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lower_code");

                    b.Property<string>("LowerDesc")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lower_desc");

                    b.Property<string>("LowerUom")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lower_uom");

                    b.Property<double?>("LowerVal")
                        .HasColumnType("double precision")
                        .HasColumnName("lower_val");

                    b.Property<string>("MilCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("mil_code");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Onshore")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("onshore");

                    b.Property<short?>("Pacific")
                        .HasColumnType("smallint")
                        .HasColumnName("pacific");

                    b.Property<string>("Sector")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<double?>("ShapeArea")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_area");

                    b.Property<double?>("ShapeLength")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_length");

                    b.Property<string>("State")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("state");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("type_code");

                    b.Property<string>("UpperCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("upper_code");

                    b.Property<string>("UpperDesc")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("upper_desc");

                    b.Property<string>("UpperUom")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("upper_uom");

                    b.Property<double?>("UpperVal")
                        .HasColumnType("double precision")
                        .HasColumnName("upper_val");

                    b.Property<short?>("UsArea")
                        .HasColumnType("smallint")
                        .HasColumnName("us_area");

                    b.Property<short?>("UsHigh")
                        .HasColumnType("smallint")
                        .HasColumnName("us_high");

                    b.Property<short?>("UsLow")
                        .HasColumnType("smallint")
                        .HasColumnName("us_low");

                    b.Property<string>("WkhrCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("wkhr_code");

                    b.Property<string>("WkhrRmk")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("wkhr_rmk");

                    b.HasKey("GlobalId");

                    b.HasIndex("Class");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("IcaoId");

                    b.HasIndex("Name");

                    b.HasIndex("State");

                    b.ToTable("airspaces", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.ChartSupplement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportCity")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("airport_city");

                    b.Property<string>("AirportCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("airport_code");

                    b.Property<string>("AirportName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("airport_name");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("NavigationalAidName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("navigational_aid_name");

                    b.HasKey("Id");

                    b.HasIndex("AirportCode");

                    b.HasIndex("NavigationalAidName");

                    b.ToTable("chart_supplement");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.CommunicationFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtccOrFssId")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("artcc_or_fss_id");

                    b.Property<string>("Cpdlc")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cpdlc");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("FacilityCode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("facility_code");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("facility_name");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("facility_type");

                    b.Property<string>("Frequency")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("frequency");

                    b.Property<string>("FrequencyUse")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("frequency_use");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("PrimaryApproachRadioCall")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)")
                        .HasColumnName("primary_approach_radio_call");

                    b.Property<string>("Remark")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("remark");

                    b.Property<string>("Sectorization")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sectorization");

                    b.Property<string>("ServicedCity")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("serviced_city");

                    b.Property<string>("ServicedCountry")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("serviced_country");

                    b.Property<string>("ServicedFacility")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("serviced_facility");

                    b.Property<string>("ServicedFacilityName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("serviced_facility_name");

                    b.Property<string>("ServicedSiteType")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("serviced_site_type");

                    b.Property<string>("ServicedState")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("serviced_state");

                    b.Property<string>("TowerHours")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("tower_hours");

                    b.Property<string>("TowerOrCommCall")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tower_or_comm_call");

                    b.HasKey("Id");

                    b.HasIndex("FacilityCode");

                    b.HasIndex("ServicedFacility");

                    b.HasIndex("ServicedState");

                    b.HasIndex("FacilityCode", "ServicedFacility", "ServicedSiteType", "ServicedState", "Frequency", "FrequencyUse", "Sectorization")
                        .IsUnique()
                        .HasFilter("\"facility_code\" IS NOT NULL AND \"serviced_facility\" IS NOT NULL AND \"serviced_site_type\" IS NOT NULL AND \"serviced_state\" IS NOT NULL AND \"frequency\" IS NOT NULL AND \"frequency_use\" IS NOT NULL AND \"sectorization\" IS NOT NULL");

                    b.ToTable("communication_frequencies", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.FaaPublicationCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleLengthDays")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_length_days");

                    b.Property<DateTime>("KnownValidDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("known_valid_date");

                    b.Property<DateTime?>("LastSuccessfulUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_update");

                    b.Property<string>("PublicationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publication_type");

                    b.HasKey("Id");

                    b.HasIndex("PublicationType")
                        .IsUnique();

                    b.ToTable("faa_publication_cycle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CycleLengthDays = 56,
                            KnownValidDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "ChartSupplement"
                        },
                        new
                        {
                            Id = 2,
                            CycleLengthDays = 28,
                            KnownValidDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "AirportDiagram"
                        },
                        new
                        {
                            Id = 3,
                            CycleLengthDays = 28,
                            KnownValidDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "NasrSubscription_Airport"
                        },
                        new
                        {
                            Id = 4,
                            CycleLengthDays = 28,
                            KnownValidDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "NasrSubscription_Frequencies"
                        },
                        new
                        {
                            Id = 5,
                            CycleLengthDays = 56,
                            KnownValidDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "Airspaces"
                        },
                        new
                        {
                            Id = 6,
                            CycleLengthDays = 56,
                            KnownValidDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "SpecialUseAirspaces"
                        },
                        new
                        {
                            Id = 7,
                            CycleLengthDays = 56,
                            KnownValidDate = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublicationType = "Obstacles"
                        });
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftId")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("AircraftPerformanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aircraft_performance_id");

                    b.Property<List<string>>("AirspaceGlobalIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("airspace_global_ids");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth0_user_id");

                    b.Property<double>("AverageWindComponent")
                        .HasColumnType("double precision")
                        .HasColumnName("average_wind_component");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_time");

                    b.Property<List<NavlogLeg>>("Legs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("legs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<List<string>>("ObstacleOasNumbers")
                        .HasColumnType("jsonb")
                        .HasColumnName("obstacle_oas_numbers");

                    b.Property<int>("PlannedCruisingAltitude")
                        .HasColumnType("integer")
                        .HasColumnName("planned_cruising_altitude");

                    b.Property<string>("RelatedFlightId")
                        .HasColumnType("text")
                        .HasColumnName("related_flight_id");

                    b.Property<List<string>>("SpecialUseAirspaceGlobalIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("special_use_airspace_global_ids");

                    b.Property<List<string>>("StateCodesAlongRoute")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_codes_along_route");

                    b.Property<double>("TotalFuelUsed")
                        .HasColumnType("double precision")
                        .HasColumnName("total_fuel_used");

                    b.Property<double>("TotalRouteDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("total_route_distance");

                    b.Property<double>("TotalRouteTimeHours")
                        .HasColumnType("double precision")
                        .HasColumnName("total_route_time_hours");

                    b.Property<List<Waypoint>>("Waypoints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("waypoints");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AircraftPerformanceId");

                    b.HasIndex("Auth0UserId");

                    b.HasIndex("Auth0UserId", "Name");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.GAirmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Altitudes")
                        .HasColumnType("jsonb")
                        .HasColumnName("altitudes");

                    b.Property<string>("Area")
                        .HasColumnType("jsonb")
                        .HasColumnName("area");

                    b.Property<string>("DueTo")
                        .HasColumnType("text")
                        .HasColumnName("due_to");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<int>("ForecastHour")
                        .HasColumnType("integer")
                        .HasColumnName("forecast_hour");

                    b.Property<string>("GeometryType")
                        .HasColumnType("text")
                        .HasColumnName("geometry_type");

                    b.Property<string>("HazardSeverity")
                        .HasColumnType("text")
                        .HasColumnName("hazard_severity");

                    b.Property<string>("HazardType")
                        .HasColumnType("text")
                        .HasColumnName("hazard_type");

                    b.Property<DateTime>("IssueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_time");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product");

                    b.Property<DateTime>("ReceiptTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receipt_time");

                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTime>("ValidTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_time");

                    b.HasKey("Id");

                    b.HasIndex("ExpireTime");

                    b.HasIndex("HazardType");

                    b.HasIndex("IssueTime");

                    b.HasIndex("Product");

                    b.HasIndex("ValidTime");

                    b.ToTable("gairmet");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Obstacle", b =>
                {
                    b.Property<string>("OasNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("oas_number");

                    b.Property<string>("Action")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("action");

                    b.Property<string>("CityName")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("city_name");

                    b.Property<string>("CountryId")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_id");

                    b.Property<string>("FaaStudyNumber")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("faa_study_number");

                    b.Property<int?>("HeightAgl")
                        .HasColumnType("integer")
                        .HasColumnName("height_agl");

                    b.Property<int?>("HeightAmsl")
                        .HasColumnType("integer")
                        .HasColumnName("height_amsl");

                    b.Property<string>("HorizontalAccuracy")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("horizontal_accuracy");

                    b.Property<string>("JulianDate")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("julian_date");

                    b.Property<decimal?>("LatDecimal")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("lat_decimal");

                    b.Property<int?>("LatDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("lat_degrees");

                    b.Property<string>("LatHemisphere")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lat_hemisphere");

                    b.Property<int?>("LatMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("lat_minutes");

                    b.Property<decimal?>("LatSeconds")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("lat_seconds");

                    b.Property<string>("Lighting")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lighting");

                    b.Property<Point>("Location")
                        .HasColumnType("geography(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<decimal?>("LongDecimal")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("long_decimal");

                    b.Property<int?>("LongDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("long_degrees");

                    b.Property<string>("LongHemisphere")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("long_hemisphere");

                    b.Property<int?>("LongMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("long_minutes");

                    b.Property<decimal?>("LongSeconds")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("long_seconds");

                    b.Property<string>("MarkIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("mark_indicator");

                    b.Property<string>("OasCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("oas_code");

                    b.Property<string>("ObstacleNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("obstacle_number");

                    b.Property<string>("ObstacleType")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("obstacle_type");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("StateId")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state_id");

                    b.Property<string>("VerificationStatus")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("verification_status");

                    b.Property<string>("VerticalAccuracy")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("vertical_accuracy");

                    b.HasKey("OasNumber");

                    b.HasIndex("HeightAgl");

                    b.HasIndex("HeightAmsl");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OasNumber")
                        .IsUnique();

                    b.HasIndex("ObstacleType");

                    b.HasIndex("StateId");

                    b.ToTable("obstacles", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Pirep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftRef")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_ref");

                    b.Property<int?>("AltitudeFtMsl")
                        .HasColumnType("integer")
                        .HasColumnName("altitude_ft_msl");

                    b.Property<string>("IcingConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("icing_condition");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<string>("ObservationTime")
                        .HasColumnType("text")
                        .HasColumnName("observation_time");

                    b.Property<string>("QualityControlFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_control_flags");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("ReceiptTime")
                        .HasColumnType("text")
                        .HasColumnName("receipt_time");

                    b.Property<string>("ReportType")
                        .HasColumnType("text")
                        .HasColumnName("report_type");

                    b.Property<string>("SkyConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("sky_condition");

                    b.Property<float?>("TempC")
                        .HasColumnType("real")
                        .HasColumnName("temp_c");

                    b.Property<string>("TurbulenceConditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("turbulence_condition");

                    b.Property<int?>("VertGustKt")
                        .HasColumnType("integer")
                        .HasColumnName("vert_gust_kt");

                    b.Property<int?>("VisibilityStatuteMi")
                        .HasColumnType("integer")
                        .HasColumnName("visibility_statute_mi");

                    b.Property<int?>("WindDirDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("wind_dir_degrees");

                    b.Property<int?>("WindSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_speed_kt");

                    b.Property<string>("WxString")
                        .HasColumnType("text")
                        .HasColumnName("wx_string");

                    b.HasKey("Id");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("ReceiptTime");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("pirep");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Runway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EdgeLightIntensity")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("edge_light_intensity");

                    b.Property<int?>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("PavementClassification")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("pavement_classification");

                    b.Property<string>("RunwayId")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("runway_id");

                    b.Property<string>("SiteNo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("site_no");

                    b.Property<string>("SurfaceTreatmentCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("surface_treatment_code");

                    b.Property<string>("SurfaceTypeCode")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("surface_type_code");

                    b.Property<int?>("WeightBearingDoubleDualTandem")
                        .HasColumnType("integer")
                        .HasColumnName("weight_bearing_double_dual_tandem");

                    b.Property<int?>("WeightBearingDualTandem")
                        .HasColumnType("integer")
                        .HasColumnName("weight_bearing_dual_tandem");

                    b.Property<int?>("WeightBearingDualWheel")
                        .HasColumnType("integer")
                        .HasColumnName("weight_bearing_dual_wheel");

                    b.Property<int?>("WeightBearingSingleWheel")
                        .HasColumnType("integer")
                        .HasColumnName("weight_bearing_single_wheel");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("Length");

                    b.HasIndex("SiteNo");

                    b.HasIndex("SurfaceTypeCode");

                    b.HasIndex("SiteNo", "RunwayId")
                        .IsUnique();

                    b.ToTable("runways", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.RunwayEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproachLightSystem")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("approach_light_system");

                    b.Property<string>("ApproachType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("approach_type");

                    b.Property<bool>("CenterlineLights")
                        .HasColumnType("boolean")
                        .HasColumnName("centerline_lights");

                    b.Property<string>("ControllingObjectCenterlineOffset")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("controlling_object_centerline_offset");

                    b.Property<int?>("ControllingObjectClearanceSlope")
                        .HasColumnType("integer")
                        .HasColumnName("controlling_object_clearance_slope");

                    b.Property<string>("ControllingObjectDescription")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("controlling_object_description");

                    b.Property<int?>("ControllingObjectDistanceFromRunway")
                        .HasColumnType("integer")
                        .HasColumnName("controlling_object_distance_from_runway");

                    b.Property<int?>("ControllingObjectHeightAboveRunway")
                        .HasColumnType("integer")
                        .HasColumnName("controlling_object_height_above_runway");

                    b.Property<string>("ControllingObjectMarkedLighted")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("controlling_object_marked_lighted");

                    b.Property<decimal?>("DisplacedThresholdElev")
                        .HasColumnType("decimal(7,1)")
                        .HasColumnName("displaced_threshold_elev");

                    b.Property<decimal?>("DisplacedThresholdLatDecimal")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("displaced_threshold_lat_decimal");

                    b.Property<int?>("DisplacedThresholdLength")
                        .HasColumnType("integer")
                        .HasColumnName("displaced_threshold_length");

                    b.Property<decimal?>("DisplacedThresholdLongDecimal")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("displaced_threshold_long_decimal");

                    b.Property<decimal?>("Elevation")
                        .HasColumnType("decimal(7,1)")
                        .HasColumnName("elevation");

                    b.Property<decimal?>("LatDecimal")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("lat_decimal");

                    b.Property<decimal?>("LongDecimal")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("long_decimal");

                    b.Property<bool>("RightHandTrafficPattern")
                        .HasColumnType("boolean")
                        .HasColumnName("right_hand_traffic_pattern");

                    b.Property<string>("RunwayEndId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("runway_end_id");

                    b.Property<bool>("RunwayEndLights")
                        .HasColumnType("boolean")
                        .HasColumnName("runway_end_lights");

                    b.Property<Guid?>("RunwayFk")
                        .HasColumnType("uuid")
                        .HasColumnName("runway_fk");

                    b.Property<string>("RunwayIdRef")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("runway_id_ref");

                    b.Property<string>("RunwayMarkingsCondition")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("runway_markings_condition");

                    b.Property<string>("RunwayMarkingsType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("runway_markings_type");

                    b.Property<bool>("RunwayVisibilityValueEquipment")
                        .HasColumnType("boolean")
                        .HasColumnName("runway_visibility_value_equipment");

                    b.Property<string>("RunwayVisualRangeEquipment")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("runway_visual_range_equipment");

                    b.Property<string>("SiteNo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("site_no");

                    b.Property<decimal?>("ThresholdCrossingHeight")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("threshold_crossing_height");

                    b.Property<decimal?>("TouchdownZoneElev")
                        .HasColumnType("decimal(7,1)")
                        .HasColumnName("touchdown_zone_elev");

                    b.Property<bool>("TouchdownZoneLights")
                        .HasColumnType("boolean")
                        .HasColumnName("touchdown_zone_lights");

                    b.Property<int?>("TrueAlignment")
                        .HasColumnType("integer")
                        .HasColumnName("true_alignment");

                    b.Property<decimal?>("VisualGlidePathAngle")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("visual_glide_path_angle");

                    b.Property<string>("VisualGlideSlopeIndicator")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("visual_glide_slope_indicator");

                    b.HasKey("Id");

                    b.HasIndex("RunwayFk");

                    b.HasIndex("RunwayFk", "RunwayEndId")
                        .IsUnique()
                        .HasFilter("\"runway_fk\" IS NOT NULL");

                    b.HasIndex("SiteNo", "RunwayIdRef", "RunwayEndId")
                        .IsUnique();

                    b.ToTable("runway_ends", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.SpecialUseAirspace", b =>
                {
                    b.Property<string>("GlobalId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("global_id");

                    b.Property<short?>("AkHigh")
                        .HasColumnType("smallint")
                        .HasColumnName("ak_high");

                    b.Property<short?>("AkLow")
                        .HasColumnType("smallint")
                        .HasColumnName("ak_low");

                    b.Property<string>("City")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("city");

                    b.Property<string>("Class")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("class");

                    b.Property<string>("CommName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("comm_name");

                    b.Property<string>("ContAgent")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("cont_agent");

                    b.Property<string>("Country")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("country");

                    b.Property<string>("DstCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dst_code");

                    b.Property<string>("Exclusion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("exclusion");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry(Polygon, 4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("GmtOffset")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("gmt_offset");

                    b.Property<string>("LevelCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("level_code");

                    b.Property<string>("LowerCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lower_code");

                    b.Property<string>("LowerDesc")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lower_desc");

                    b.Property<string>("LowerUom")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lower_uom");

                    b.Property<string>("LowerVal")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lower_val");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Onshore")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("onshore");

                    b.Property<short?>("Pacific")
                        .HasColumnType("smallint")
                        .HasColumnName("pacific");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("remarks");

                    b.Property<string>("Sector")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<float?>("ShapeArea")
                        .HasColumnType("real")
                        .HasColumnName("shape_area");

                    b.Property<float?>("ShapeLength")
                        .HasColumnType("real")
                        .HasColumnName("shape_length");

                    b.Property<string>("State")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("state");

                    b.Property<string>("TimesOfUse")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("times_of_use");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("type_code");

                    b.Property<string>("UpperCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("upper_code");

                    b.Property<string>("UpperDesc")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("upper_desc");

                    b.Property<string>("UpperUom")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("upper_uom");

                    b.Property<string>("UpperVal")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("upper_val");

                    b.Property<short?>("UsArea")
                        .HasColumnType("smallint")
                        .HasColumnName("us_area");

                    b.Property<short?>("UsHigh")
                        .HasColumnType("smallint")
                        .HasColumnName("us_high");

                    b.Property<short?>("UsLow")
                        .HasColumnType("smallint")
                        .HasColumnName("us_low");

                    b.HasKey("GlobalId");

                    b.HasIndex("Class");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("State");

                    b.ToTable("special_use_airspaces", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Taf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BulletinTime")
                        .HasColumnType("text")
                        .HasColumnName("bulletin_time");

                    b.Property<float?>("ElevationM")
                        .HasColumnType("real")
                        .HasColumnName("elevation_m");

                    b.Property<string>("Forecast")
                        .HasColumnType("jsonb")
                        .HasColumnName("forecast");

                    b.Property<string>("IssueTime")
                        .HasColumnType("text")
                        .HasColumnName("issue_time");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("StationId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("station_id");

                    b.Property<string>("ValidTimeFrom")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_from");

                    b.Property<string>("ValidTimeTo")
                        .HasColumnType("text")
                        .HasColumnName("valid_time_to");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("ValidTimeFrom");

                    b.HasIndex("StationId", "ValidTimeFrom");

                    b.ToTable("taf");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.WeightBalanceProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftId")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("ArmUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arm_units");

                    b.Property<List<CgEnvelope>>("CgEnvelopes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cg_envelopes");

                    b.Property<string>("DatumDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("datum_description");

                    b.Property<double>("EmptyWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("empty_weight");

                    b.Property<double>("EmptyWeightArm")
                        .HasColumnType("double precision")
                        .HasColumnName("empty_weight_arm");

                    b.Property<List<LoadingStation>>("LoadingStations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("loading_stations");

                    b.Property<double?>("MaxLandingWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_landing_weight");

                    b.Property<double?>("MaxRampWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_ramp_weight");

                    b.Property<double>("MaxTakeoffWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_takeoff_weight");

                    b.Property<double?>("MaxZeroFuelWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_zero_fuel_weight");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profile_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("WeightUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weight_units");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProfileName")
                        .IsUnique();

                    b.ToTable("weight_balance_profiles", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Metar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AltimInHg")
                        .HasColumnType("real")
                        .HasColumnName("altim_in_hg");

                    b.Property<float?>("DewpointC")
                        .HasColumnType("real")
                        .HasColumnName("dewpoint_c");

                    b.Property<float?>("ElevationM")
                        .HasColumnType("real")
                        .HasColumnName("elevation_m");

                    b.Property<string>("FlightCategory")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("flight_category");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<float?>("MaxT24hrC")
                        .HasColumnType("real")
                        .HasColumnName("maxT24hr_c");

                    b.Property<float?>("MaxTC")
                        .HasColumnType("real")
                        .HasColumnName("maxT_c");

                    b.Property<string>("MetarType")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("metar_type");

                    b.Property<float?>("MinT24hrC")
                        .HasColumnType("real")
                        .HasColumnName("minT24hr_c");

                    b.Property<float?>("MinTC")
                        .HasColumnType("real")
                        .HasColumnName("minT_c");

                    b.Property<string>("ObservationTime")
                        .HasColumnType("text")
                        .HasColumnName("observation_time");

                    b.Property<float?>("Pcp24hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp24hr_in");

                    b.Property<float?>("Pcp3hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp3hr_in");

                    b.Property<float?>("Pcp6hrIn")
                        .HasColumnType("real")
                        .HasColumnName("pcp6hr_in");

                    b.Property<float?>("PrecipIn")
                        .HasColumnType("real")
                        .HasColumnName("precip_in");

                    b.Property<string>("QualityControlFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_control_flags");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<float?>("SeaLevelPressureMb")
                        .HasColumnType("real")
                        .HasColumnName("sea_level_pressure_mb");

                    b.Property<string>("SkyCondition")
                        .HasColumnType("jsonb")
                        .HasColumnName("sky_condition");

                    b.Property<float?>("SnowIn")
                        .HasColumnType("real")
                        .HasColumnName("snow_in");

                    b.Property<string>("StationId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("station_id");

                    b.Property<float?>("TempC")
                        .HasColumnType("real")
                        .HasColumnName("temp_c");

                    b.Property<float?>("ThreeHrPressureTendencyMb")
                        .HasColumnType("real")
                        .HasColumnName("three_hr_pressure_tendency_mb");

                    b.Property<int?>("VertVisFt")
                        .HasColumnType("integer")
                        .HasColumnName("vert_vis_ft");

                    b.Property<string>("VisibilityStatuteMi")
                        .HasColumnType("text")
                        .HasColumnName("visibility_statute_mi");

                    b.Property<string>("WindDirDegrees")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("wind_dir_degrees");

                    b.Property<int?>("WindGustKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_gust_kt");

                    b.Property<int?>("WindSpeedKt")
                        .HasColumnType("integer")
                        .HasColumnName("wind_speed_kt");

                    b.Property<string>("WxString")
                        .HasColumnType("text")
                        .HasColumnName("wx_string");

                    b.HasKey("Id");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("StationId");

                    b.HasIndex("StationId", "ObservationTime");

                    b.ToTable("metar");
                });

            modelBuilder.Entity("flight_airspaces", b =>
                {
                    b.Property<string>("flight_id")
                        .HasColumnType("text");

                    b.Property<string>("airspace_global_id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("flight_id", "airspace_global_id");

                    b.HasIndex("airspace_global_id");

                    b.ToTable("flight_airspaces", (string)null);
                });

            modelBuilder.Entity("flight_obstacles", b =>
                {
                    b.Property<string>("flight_id")
                        .HasColumnType("text");

                    b.Property<string>("obstacle_oas_number")
                        .HasColumnType("varchar(10)");

                    b.HasKey("flight_id", "obstacle_oas_number");

                    b.HasIndex("obstacle_oas_number");

                    b.ToTable("flight_obstacles", (string)null);
                });

            modelBuilder.Entity("flight_special_use_airspaces", b =>
                {
                    b.Property<string>("flight_id")
                        .HasColumnType("text");

                    b.Property<string>("special_use_airspace_global_id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("flight_id", "special_use_airspace_global_id");

                    b.HasIndex("special_use_airspace_global_id");

                    b.ToTable("flight_special_use_airspaces", (string)null);
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.AircraftPerformanceProfile", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("PerformanceProfiles")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Flight", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PreflightApi.Domain.Entities.AircraftPerformanceProfile", "AircraftPerformanceProfile")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftPerformanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("AircraftPerformanceProfile");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Runway", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Airport", null)
                        .WithMany()
                        .HasForeignKey("SiteNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.RunwayEnd", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Runway", "Runway")
                        .WithMany("RunwayEnds")
                        .HasForeignKey("RunwayFk")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Runway");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.WeightBalanceProfile", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("WeightBalanceProfiles")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("flight_airspaces", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Airspace", null)
                        .WithMany()
                        .HasForeignKey("airspace_global_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreflightApi.Domain.Entities.Flight", null)
                        .WithMany()
                        .HasForeignKey("flight_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("flight_obstacles", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Flight", null)
                        .WithMany()
                        .HasForeignKey("flight_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreflightApi.Domain.Entities.Obstacle", null)
                        .WithMany()
                        .HasForeignKey("obstacle_oas_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("flight_special_use_airspaces", b =>
                {
                    b.HasOne("PreflightApi.Domain.Entities.Flight", null)
                        .WithMany()
                        .HasForeignKey("flight_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreflightApi.Domain.Entities.SpecialUseAirspace", null)
                        .WithMany()
                        .HasForeignKey("special_use_airspace_global_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Aircraft", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("PerformanceProfiles");

                    b.Navigation("WeightBalanceProfiles");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.AircraftPerformanceProfile", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("PreflightApi.Domain.Entities.Runway", b =>
                {
                    b.Navigation("RunwayEnds");
                });
#pragma warning restore 612, 618
        }
    }
}
